print("Segunda Prueba")
print("otra prueba mas")
print("solo otra prueba")
print("Segunda Prueba")
print("otra prueba mas")
print("solo otra prueba")
print("Segunda Prueba")
print("otra prueba mas")
print("solo otra prueba")